name: Draw Keymaps
on:
  workflow_dispatch: # 手動実行用
  push:
    paths:
      - "config/boards/shields/LiNEA40/LiNEA40.keymap" # キーマップが変更された時に自動実行
      - "keymap_drawer.config.yaml"     
      - "config/boards/shields/LiNEA40/LiNEA40.dtsi"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@f9cf9d3677368a7fb1dc505c51b8156fafa66fe2
    with:
      commit_message: "[Draw] ${{ github.event.head_commit.message || 'Update keymap drawing' }}"
      amend_commit: false
      keymap_patterns: "config/*.keymap" # 読み込むキーマップのパス
      json_path: "config"
      config_path: "keymap_drawer.config.yaml" # 設定ファイル（任意）
      output_folder: "img" # 画像を保存するフォルダ名
      destination: "both"
